# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 08a574572de5e46bc1bf22087e719f3385034430e212668672464ebc8241a399dde63e2476811b35874b40533d3104916a2116c72da1698681aaf6146cc19c05

test:
  secret_key_base: 85294e885c4e1c7c904302e759e98d6dec14c86760a116d3cc90e5cd03b75b53caf407003a7a2e3a9c3207528bc199fa06ed227dba3b38b3450614b802430525

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
